### ISSUE TITLE
Composing Optional with Iso and Prism prevents inserting value

### ISSUE THREAD

**Issue by Odomontois** [julien-truffaut/Monocle#301]
Some person [here][SO] asks for help
If I'm not misundersanding `index` should work as `upsert` already and does not work because of composition.

Composing `Optional` regarding [that][Optional] with anything from `Iso` and up to `Optional` is   happening like 
 ```scala
def composePrism[C, D](other: PPrism[A, B, C, D]): POptional[S, T, C, D] =
    composeOptional(other.asOptional)
```
setting new value  in this composition is like
```scala 
def set(d: D): S => T =
        self.modify(other.set(d))
```
`modify` for `Optional` will modify only existent field so if we compose `Optional`with anything else, it becomes `update` only, it could not `insert` 

while for `PPrism` we could use another definition like 

```scala
  def set(d: D): S => T =
    self.set(other.reverseGet(d))
```
which able to insert new value even if original object has nothing here yet

So can we have specialized compose for `Iso` and `Prism` ?

[SO]:http://stackoverflow.com/questions/33928625/scala-how-to-upsert-field-value-in-monocle
[Optional]:https://github.com/julien-truffaut/Monocle/blob/master/core/src/main/scala/monocle/Optional.scala

**Comment by julien-truffaut** [comment]
Thank you very much @Odomontois for raising the question. I answered in SO regarding this particular example.

Regarding the general question, it is expected that you cannot insert or delete a value in an Maplike data structure with an `Optional`. Here is why:

```scala
def index(key: K): Optional[Map[K, V], V]
``` 

so `index` creates a `Optional` between a `Map[K, V]` and a specific value at index `key` with type `V`. Here is the type signature of `set` and `modify`: 

```scala
def set(v: V)(m: Map[K, V]): Map[K, V]
def modify(f: V => V)(m: Map[K, V]): Map[K, V]
```

`set` can be seen as a weaker `modify`:
```scala
def set(v: V)(m: Map[K, V]): Map[K, V] = modify(_ => v)(m)
```

Now we can see why we cannot insert or delete via `index`, we only have a function `V => V`. In order to `insert` or `delete` we need a function `Option[V] => Option[V]`

**Comment by Odomontois** [comment]
Ok. It's clear now.
