### ISSUE TITLE
2.11.8 support

### ISSUE THREAD

**Issue by acruise** [julien-truffaut/Monocle#330]
It'd be nice to have a new build of 1.2.0 with macro support for 2.11.8. Thanks!

**Comment by julien-truffaut** [comment]
what would be the difference if the lib is compiled against 2.11.7 or 2.11.8?

**Comment by aoiroaoino** [comment]
related to macro's issue is following...?
https://issues.scala-lang.org/browse/SI-9616?jql=project%20%3D%20SI%20AND%20resolution%20%3D%20Fixed%20AND%20fixVersion%20%3D%20%22Scala%202.11.8%22%20AND%20text%20~%20%22macro%22%20ORDER%20BY%20component%20ASC%2C%20priority%20DESC
hmm..... I think that necessarily there is no need to release.

However, https://github.com/sbt/sbt/issues/2076 has been fixed in v2.11.8.
We can try to use `-Ybackend:GenBCode` option. :smile:

**Comment by julien-truffaut** [comment]
@aoiroaoino do you all the scalac options we need to benefit from java8? It would be nice to give it a try.

**Comment by xuwei-k** [comment]
> all the scalac options we need to benefit from java8

- https://github.com/scalaz/scalaz/commit/e3f01cdfb399412b400b9b2250ad755516d7ab2f
- https://github.com/scala/make-release-notes/blob/9cfbdc8c92f94/experimental-backend.md#emitting-java-8-style-lambdas
- https://github.com/lrytz/experimental-backend-2.11/blob/76b7a45b73a08e5b17641d3fc179e9861bba2f80/build.sbt

**Comment by julien-truffaut** [comment]
Awesome, thanks @xuwei-k

**Comment by julien-truffaut** [comment]
can I close it? Or someone need a release?

**Comment by aoiroaoino** [comment]
I think that this issue has finished :+1:
